[project]
name = "sweaver"
version = "0.1.0"
description = "Harmonic-domain manipulation of electomagnetic beams for CMB analysis"
readme = "README.md"
authors = [{ name = "Maurizio Tomasi", email = "maurizio.tomasi@unimi.it" }]
requires-python = ">=3.11"
license = "GPL-3.0-or-later"
license-files = ["LICENSE.txt"]
keywords = [
  "spherical harmonics",
  "beam pattern",
  "CMB",
  "TICRA GRASP",
  "antenna",
  "spin-weighted",
  "cosmology",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
  "astropy>=7.2.0",
  "ducc0>=0.40.0",
  "numpy>=1.26.0",
  "scipy>=1.17.0",
  "scipy-stubs~=1.17.0",
]

[project.urls]
Homepage = "https://github.com/ziotom78/sweaver"
Repository = "https://github.com/ziotom78/sweaver"
Issues = "https://github.com/ziotom78/sweaver/issues"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "hypothesis>=6.151.2",
  "mkdocs-material>=9.7.1",
  "mkdocstrings-python>=2.0.1",
  "nox>=2026.2.9",
  "nox-uv>=0.7.1",
  "prek>=0.3.2",
  "pytest>=9.0.2",
  "pytest-cov>=7.0.0",
  "ruff>=0.15.15",
  "ty==0.0.28",
]
visualization = [
  "jupyterlab>=4.5.5",
  "matplotlib>=3.10.8",
  "ipywidgets>=8.1.8",
  "plotly>=6.5.2",
]
docs = ["sphinx>=8.2.1", "sphinx-rtd-theme>=3.0.2", "matplotlib>=3.10.8"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=src/sweaver"

[tool.uv_build]
include = ["src/sweaver/test_data/**/*", "src/sweaver/py.typed"]
